# Tensor Basics

Numpy to tensor and some basics

In [1]:
import torch

In [2]:
x =  torch.empty(2,3)
x

tensor([[-4.9384e-39,  5.3389e-43, -4.9384e-39],
        [ 5.3389e-43, -1.2394e-38,  5.3389e-43]])

In [4]:
y= torch.rand(2,3,4)
y

tensor([[[0.1495, 0.2676, 0.3049, 0.2750],
         [0.2394, 0.0614, 0.5467, 0.3394],
         [0.8833, 0.9106, 0.8058, 0.1013]],

        [[0.9797, 0.3648, 0.1466, 0.0433],
         [0.4520, 0.7845, 0.0099, 0.0172],
         [0.2617, 0.3466, 0.6870, 0.2733]]])

In [7]:
z = torch.ones(2,2)
z

tensor([[1., 1.],
        [1., 1.]])

In [9]:
m = torch.ones(2,2, dtype= torch.double)#float16
m

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [11]:
print(m.size())

torch.Size([2, 2])


In [14]:
h= torch.tensor([1.2, 1.])
h

tensor([1.2000, 1.0000])

In [16]:
type(h)

torch.Tensor

In [19]:
x= torch.rand(2,3)
y= torch.rand(2,3)
x

tensor([[0.7122, 0.0021, 0.9954],
        [0.5527, 0.6483, 0.4960]])

In [21]:
y

tensor([[0.3498, 0.9510, 0.2612],
        [0.2224, 0.4601, 0.8452]])

In [23]:
z= x+y
z

tensor([[1.0620, 0.9530, 1.2567],
        [0.7752, 1.1084, 1.3412]])

In [28]:
z= torch.add(x,y)
z

tensor([[1.7743, 0.9551, 2.2521],
        [1.3279, 1.7566, 1.8372]])

In [29]:
y

tensor([[1.0620, 0.9530, 1.2567],
        [0.7752, 1.1084, 1.3412]])

In [31]:
#inplace add with add_
y.add_(x)
y

tensor([[2.4865, 0.9572, 3.2475],
        [1.8806, 2.4049, 2.3332]])

In [33]:
#same for sub
z1= torch.sub(x,y)
z1

tensor([[-1.7743, -0.9551, -2.2521],
        [-1.3279, -1.7566, -1.8372]])

In [36]:
z=x-y
z

tensor([[-1.7743, -0.9551, -2.2521],
        [-1.3279, -1.7566, -1.8372]])

In [38]:
y

tensor([[2.4865, 0.9572, 3.2475],
        [1.8806, 2.4049, 2.3332]])

In [40]:
y.sub_(x)
y

tensor([[1.0620, 0.9530, 1.2567],
        [0.7752, 1.1084, 1.3412]])

### same for mul - * and div - / 

In [43]:
x= torch.rand(5,3)
x

tensor([[0.4244, 0.2378, 0.1686],
        [0.7752, 0.4780, 0.7811],
        [0.1390, 0.7367, 0.0492],
        [0.7122, 0.4733, 0.7879],
        [0.5814, 0.6558, 0.4885]])

In [45]:
x[1,:] #1 is the second(0,1,2...) row 行 and ：is all columns 

tensor([0.7752, 0.4780, 0.7811])

In [47]:
x[1,1] # the second row and second column

tensor(0.4780)

In [49]:
x[1,1].item() # get the one element with actual value

0.47803258895874023

In [52]:
x= torch.rand(4,4)
y= x.view(16)# reshape from 4*4 to 16*1
y

tensor([0.2843, 0.9532, 0.4500, 0.8673, 0.1187, 0.9415, 0.0999, 0.1147, 0.8233,
        0.6926, 0.3265, 0.4036, 0.3597, 0.7581, 0.4455, 0.0368])

In [57]:
z= x.view(-1,8)# reshape from 4*4 to any (-1 is decide by itself)* 8
z

tensor([[0.2843, 0.9532, 0.4500, 0.8673, 0.1187, 0.9415, 0.0999, 0.1147],
        [0.8233, 0.6926, 0.3265, 0.4036, 0.3597, 0.7581, 0.4455, 0.0368]])

In [58]:
z.size

<function Tensor.size>

In [60]:
z.size()

torch.Size([2, 8])

## Numpy to tensor

In [66]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [67]:
type(a)

torch.Tensor

In [68]:
b= a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [70]:
type(b)

numpy.ndarray

## note inplace operation when pointing the same place

In [74]:
a.add_(1)
a

tensor([3., 3., 3., 3., 3.])

In [76]:
b

array([3., 3., 3., 3., 3.], dtype=float32)

## tensor to numpy

In [80]:
h= torch.from_numpy(b)
h

tensor([3., 3., 3., 3., 3.])

In [88]:
b+=1 #inplace operation from numpy to tensor
b


array([7., 7., 7., 7., 7.], dtype=float32)

In [89]:
h

tensor([7., 7., 7., 7., 7.])

In [99]:
#windows
if torch.cuda.is_available():
    device =  torch.device("cuda")
    x= torch.ones(5,device= device)#specify the gpu variable
    y= torch.ones(5)
    y= y.to(device)# or you can define it then move to gpu
    z= x+y
    z = z.to("cpu")
    print(z)

tensor([2., 2., 2., 2., 2.])


In [100]:
x= torch.ones(5,requires_grad =True)# need to caculate the gradient

## gradient

In [102]:
x= torch.randn(3)
x

tensor([0.8676, 0.4958, 0.0943])

In [104]:
x= torch.randn(3, requires_grad =True)# need to caculate the gradient
x

tensor([ 0.8662, -0.1341,  1.2969], requires_grad=True)

In [106]:
y = x+2

![VS](figures/BB.PNG)

In [108]:
y # we can see backward for add

tensor([2.8662, 1.8659, 3.2969], grad_fn=<AddBackward0>)

In [110]:
z=y*y*2 # we can see backward for multiply
z

tensor([16.4307,  6.9629, 21.7393], grad_fn=<MulBackward0>)

In [117]:
h = z.mean()
h

tensor(15.0443, grad_fn=<MeanBackward0>)

In [118]:
h.backward() #dz/dx but it can not go second time and the requires_grad should be True

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [120]:
x.grad

tensor([3.8217, 2.4878, 4.3959])

![VS](figures/chain.PNG)

In [122]:
v =torch.tensor([0.1,1.0,0.1],dtype=torch.float32)
v

tensor([0.1000, 1.0000, 0.1000])

In [143]:
b=y*y

b.backward(v)
x.grad

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## caculate with no gradient

In [130]:
x = torch.randn(3, requires_grad=True)
x
#x.requires_grad_(False)
#x.detach()
#with torch.no_grad()

tensor([0.7725, 0.3541, 0.0081], requires_grad=True)

In [132]:
x.requires_grad_(False)

tensor([0.7725, 0.3541, 0.0081])

In [139]:
x = torch.randn(3, requires_grad=True)
y=x.detach()
y

tensor([-2.0816, -0.4068, -0.2405])

In [140]:
x = torch.randn(3, requires_grad=True)
with torch.no_grad():
    y=x+2
y

tensor([3.3204, 2.7357, 1.3388])

In [142]:
x

tensor([ 1.3204,  0.7357, -0.6612], requires_grad=True)

## accumulate the gradient

In [146]:
w = torch.ones(4, requires_grad=True)
for epoch in range(1):
    model_output =  (w*3).sum()
    model_output.backward()
    
w.grad    
    

tensor([3., 3., 3., 3.])

In [148]:
w = torch.ones(4, requires_grad=True)
for epoch in range(2):
    model_output =  (w*3).sum()
    model_output.backward()
    
w.grad  

tensor([6., 6., 6., 6.])

In [150]:
w = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output =  (w*3).sum()
    model_output.backward()
    
w.grad  

tensor([9., 9., 9., 9.])

In [153]:
w = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output =  (w*3).sum()
    model_output.backward()
    print(w.grad )
    w.grad.zero_()
 

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [156]:
#opt = torch.optim.SGD(w,lr=0.01)
#opt.step()
#opt.zero_grad()
#we should also prevent the optimizer sumup the gradient too

![VS](figures/cr.PNG)

![VS](figures/crbp.PNG)

![VS](figures/crbp1.PNG)

In [6]:
import torch
x= torch.tensor(1.0)
y= torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad = True)

#foward pass and compute loss
y_hat = w*x
loss = (y_hat-y)**2
loss

tensor(1., grad_fn=<PowBackward0>)

In [7]:
#backward pass
loss.backward()
w.grad

tensor(-2.)

In [8]:
#update weight

![VS](figures/man.PNG)

In [30]:
import numpy as np

#f=w*x
# =2*x
#X= np.array([1,2,3,4],dtype=np.float32)
#Y= np.array([2,4,6,8],dtype=np.float32)
X= torch.tensor([1,2,3,4],dtype=torch.float32)
Y= torch.tensor([2,4,6,8],dtype=torch.float32)
w =0.0

#model prediction

def forward(x):
     return w*x


#loss =MSE

def loss(y, y_predicted):
    return ((y_predicted-y)**2).mean()

     



#gradient
#MSE = 1/N*(w*x-y)**2
#dJ/dw = 1/N 2x(w*x-y)

def gradient(x,y,y_prediected):
    return np.dot(2*x, y_pred-y).mean()
a = forward(5)
print(f'Prediection before training:f(5) = {a:.8f}')

Prediection before training:f(5) = 0.00000000


In [31]:


#Training
learning_rate=0.1
n_iters =10

for epoch in range(n_iters):
    #prediction = forward pass
    y_pred = forward(X)
    
    #loss
    l= loss(Y,y_pred)
    
    #gradients
    dw = gradient(X,Y,y_pred)
    
    # update weights
    w-=learning_rate*dw
    
    if epoch%1 == 0:
        print(f'epoch {epoch+1}:w = {w:.3f}, loss ={l:.8f}')
        
print(f'Prediection before training:f(5) = {forward(5):.3f}')

epoch 1:w = 12.000, loss =30.00000000
epoch 2:w = -48.000, loss =750.00000000
epoch 3:w = 252.000, loss =18750.00000000
epoch 4:w = -1248.000, loss =468750.00000000
epoch 5:w = 6252.000, loss =11718750.00000000
epoch 6:w = -31248.000, loss =292968768.00000000
epoch 7:w = 156252.000, loss =7324218368.00000000
epoch 8:w = -781248.000, loss =183105470464.00000000
epoch 9:w = 3906252.000, loss =4577636646912.00000000
epoch 10:w = -19531247.200, loss =114440913551360.00000000
Prediection before training:f(5) = {forward(5):.3f}
